// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/sergeygardner/meal-planner-api/domain/entity"
	"github.com/sergeygardner/meal-planner-api/domain/response"
)

type AuthOps struct {
	AuthCredentials  *response.AuthConfirmation `json:"AuthCredentials,omitempty"`
	AuthConfirmation *response.AuthToken        `json:"AuthConfirmation,omitempty"`
	AuthRegister     *entity.User               `json:"AuthRegister,omitempty"`
}
